/**
 * PROVA SECRET
 * Jupiter a Travel Multi-Connectors API
 *
 * OpenAPI spec version: 1.0-modelsdashboard
 * Contact: contacts@linkswiss.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { EEnvironment } from './eEnvironment';
import { EH2HConnectorCode } from './eH2HConnectorCode';
import { EH2HConnectorType } from './eH2HConnectorType';
import { EH2HOperation } from './eH2HOperation';
import { OperationConstraints } from './operationConstraints';


export interface BaseConnectorSettings { 
    ConnectorOperationsConstraints?: any;
    ConnectorCode?: EH2HConnectorCode;
    Environment?: EEnvironment;
    DisabledConnectorTypes?: Array<EH2HConnectorType>;
    EnabledConnectorTypes?: Array<EH2HConnectorType>;
    DisabledOperations?: Array<EH2HOperation>;
    EnabledOperations?: Array<EH2HOperation>;
    Version?: string;
}
