/**
 * PROVA SECRET
 * Jupiter a Travel Multi-Connectors API
 *
 * OpenAPI spec version: 1.0-modelsdashboard
 * Contact: contacts@linkswiss.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EH2HConnectorCode = 'UNKNOWN' | 'BOOKING_DOT_COM' | 'SABRE_SYNXIS' | 'AMADEUS' | 'SABRE' | 'A_SAMPLE' | 'TRAVELFUSION';

export const EH2HConnectorCode = {
    UNKNOWN: 'UNKNOWN' as EH2HConnectorCode,
    BOOKINGDOTCOM: 'BOOKING_DOT_COM' as EH2HConnectorCode,
    SABRESYNXIS: 'SABRE_SYNXIS' as EH2HConnectorCode,
    AMADEUS: 'AMADEUS' as EH2HConnectorCode,
    SABRE: 'SABRE' as EH2HConnectorCode,
    ASAMPLE: 'A_SAMPLE' as EH2HConnectorCode
};
