/**
 * PROVA SECRET
 * Jupiter a Travel Multi-Connectors API
 *
 * OpenAPI spec version: 1.0-modelsdashboard
 * Contact: contacts@linkswiss.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EH2HConnectorType = 'HOTEL' | 'FLIGHT' | 'TOUR' | 'TRAIN' | 'FERRIES';

export const EH2HConnectorType = {
    HOTEL: 'HOTEL' as EH2HConnectorType,
    FLIGHT: 'FLIGHT' as EH2HConnectorType,
    TOUR: 'TOUR' as EH2HConnectorType,
    TRAIN: 'TRAIN' as EH2HConnectorType,
    FERRIES: 'FERRIES' as EH2HConnectorType
};