/**
 * PROVA SECRET
 * Jupiter a Travel Multi-Connectors API
 *
 * OpenAPI spec version: 1.0-modelsdashboard
 * Contact: contacts@linkswiss.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JwtSettings { 
    Secret?: string;
    JwtExpireMinutes?: number;
    JwtRefreshExpireMinutes?: number;
    JwtDashboardAudience?: string;
    JwtApiAudience?: string;
}